name: Print Changed Folders
on:
  push:
    branches:
      - main

jobs:
  print-changed-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in apps folder
        id: check-changes
        run: |
          CHANGED_FOLDERS=$(git diff --name-only HEAD^ HEAD | grep '^apps/' | cut -d/ -f2- | cut -d/ -f1 | sort -u)
          echo "::set-output name=folders::$CHANGED_FOLDERS"

      - name: Print folder names
        run: |
          echo "Changed folders:"
          IFS=$'\n' read -rd '' -a FOLDERS <<< "${{ steps.check-changes.outputs.folders }}"
          for folder in "${FOLDERS[@]}"; do
            echo "- $folder"
          done

