name: Detect Changed Folders

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        continue-on-error: true

      - name: Identify changed folders
        id: identify-changed-folders
        run: |
          changed_files=$(cat changed_files.txt)
          apps_folder="apps"
          if echo "$changed_files" | grep -q "$apps_folder"; then
            # Use a loop to iterate through changed files and extract folder names
            while read -r file; do
              if [[ -d "$file" && "$file" != "$apps_folder" ]]; then
                folder_name=$(basename "$file")
                echo "Changed folder: $folder_name"
              fi
            done <<< "$changed_files"
          else
            echo "No changes detected in the 'apps' folder."
          fi
        continue-on-error: true

