name: Monitor Folder Changes
on:
  push:
    branches:
      - main
jobs:
  check-folder-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List changed files
        run: |
          changed_folders=""
          git fetch origin main:main
          git checkout -b temp-branch main
          changed_files=$(git diff --name-only main)

          echo "Changed files:"
          echo "$changed_files"

          for file in $changed_files; do
            echo "Checking file: $file"
            if [[ $file == apps/* ]]; then
              # Extract the folder name inside 'apps'
              folder=$(dirname "$file" | cut -d '/' -f 2)
              if [[ ! $changed_folders == *"$folder"* ]]; then
                changed_folders+=" $folder"
                echo "The folder $folder has changed"
              fi
            fi
          done
          echo "changed_folders=$changed_folders" >> $GITHUB_ENV
          echo "Final list of folders that were updated: $changed_folders"
          IFS=" " read -ra folder_array <<< "${changed_folders}"
          # Print the array
          echo "Array of folders: ${folder_array[@]}"
